site_name: Sweet Validation

theme:
  name: material

nav:
  - Home: index.md
  - Components:
    - Overview: components/overview.md
    - Registry: components/registries.md
    - SchemaManager: components/schema_manager.md
    - Validators: components/validators.md
    - Storage: components/storage.md
  - Introduction to Frictionless: frictionless/frictionless.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            toc_levels: 4