site_name: My Docs

theme:
  name: material

nav:
  - Home: index.md
  - API Reference: api.md
  - Introduction to Frictionless: frictionless/frictionless.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            show_source: true
            how_root_heading: true

