name: Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Enables manual triggering of the workflow

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    # - name: Install uv
    #   uses: astral-sh/setup-uv@v5
    #   with:
    #     # Install a specific version of uv.
    #     version: "0.5.25"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install ruff pytest coverage
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Test and coverage with pytest
    #   run: |
    #     coverage run -m pytest
    #     coverage report
