name: Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Enables manual triggering of the workflow

permissions:
  contents: read

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --hook-stage pre-push

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.26"
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
    - run: mkdir coverage
    - run: uv export --all-extras --no-hashes | awk '{print $1}' FS=' ;' > requirements.txt
    - run: pip install -r requirements.txt
    - run: coverage run -m pytest
    - run: coverage report

